const data_archive = {
    cardData: [
{
    id:29,
    img: '/img/teengo-600x380.gif',
    title: 'Wallet app',
    desc: 'Diseño UX/UI de la App (WIP).',
    link: 'https://www.behance.net/gallery/156573117/Wallet-App-WIP',
    muted: 'UX/UI',
},
{
    id:24,
    img: '/img/donapp-600x380.jpg',
    title: 'Donation app',
    desc: 'Caso de estudio UX/UI.',
    link: 'https://www.behance.net/gallery/122906011/DonApp-UXUI-Design',
    muted: 'UX/UI',
},
{
    id:27,
    img: '/img/venmo-600x380.jpg',
    title: 'Venmo',
    desc: 'Diseño gráfico & UI orientado a marketing.',
    link: 'https://www.behance.net/gallery/143438131/Venmo-Graphic-UI-Design',
    muted: 'Marketing design & UI/UX',
},
{
    id:26,
    img: '/img/apple-600x380.jpg',
    title: 'Apple',
    desc: 'Implementación de micrositio "11 Razones".',
    link: 'https://latam.ingrammicro.com/apple_colombia',
    muted: 'Website',
},
{
    id:25,
    img: '/img/despegar-600x380.jpg',
    title: 'Despegar',
    desc: 'Diseño gráfico & UI orientado a marketing.',
    link: 'https://www.behance.net/gallery/96941755/Despegar-APP-web',
    muted: 'Marketing design & UX/UI',
},
// {
//     id:28,
//     img: '/img/kaspersky-600x380.jpg',
//     title: 'Kaspersky',
//     desc: 'Micrositio Kaspersky Security.',
//     link: 'https://latam.ingrammicro.com/kaspersky',
//     muted: 'Website',
// },
{
    id:23,
    img: '/img/mascotapp-600x380.jpg',
    title: 'Saving Pets app',
    desc: 'Caso de estudio UX/UI.',
    link: 'https://www.behance.net/gallery/45613945/MascotApp-UXUI-Design',
    muted: 'UX/UI',
},
// {
//     id:5,
//     img: '/img/cloudhost-600x380.jpg',
//     title: 'Cloudhost',
//     desc: 'Sitio empresa con e-commerce integrado.',
//     link: 'https://cloudhostla.com.ar',
//     muted: 'React JS',
// },
// {
//     id:22,
//     img: '/img/aws-600x380.jpg',
//     title: 'Amazon Web Services',
//     desc: 'Micrositio para webinars.',
//     link: 'https://latam.ingrammicro.com/ingramcloud_aws_webinars',
//     muted: 'Website',
// },
// {
//     id:21,
//     img: '/img/cisco-600x380.jpg',
//     title: 'Cisco',
//     desc: 'Cisco Back to School.',
//     link: 'https://latam.ingrammicro.com/cisco_summer_school',
//     muted: 'Website',
// },                
// {
//     id:20,
//     img: '/img/hpevm-600x380.jpg',
//     title: 'HP Enterprise',
//     desc: 'Sitio Vertical Markets.',
//     link: 'https://latam.ingrammicro.com/hpe_vm',
//     muted: 'Website',
// },
// {
//     id:19,
//     img: '/img/wom-600x380.jpg',
//     title: 'WOM',
//     desc: 'Diseño UX. Portal de servicios al cliente.',
//     link: 'https://www.behance.net/gallery/120622081/WOM-Customer-Portal-UXUI-Design',
//     muted: 'UX/UI',
// },
// {
//     id:18,
//     img: '/img/hpealletra-600x380.jpg',
//     title: 'HPE Alletra',
//     desc: 'Infraestructura de datos en la nube.',
//     link: 'https://latam.ingrammicro.com/HPE-Alletra',
//     muted: 'Website',
// },
// {
//     id:17,
//     img: 'img/logmein-600x380.jpg',
//     title: 'LogMeIn',
//     desc: 'Soluciones de tecnología colaborativa.',
//     link: 'https://latam.ingrammicro.com/logmein',
//     muted: 'Website',
// },
// {
//     id:16,
//     img: 'img/solucionesim-600x380.jpg',
//     title: 'Soluciones IM',
//     desc: 'Sitio con todas las soluciones de Ingram Micro.',
//     link: 'https://latam.ingrammicro.com/soluciones-im_home',
//     muted: 'Website',
// },
// {
//     id:15,
//     img: 'img/quest-600x380.jpg',
//     title: 'Ingram Quest',
//     desc: 'Administración de sistemas y bases de datos.',
//     link: 'https://latam.ingrammicro.com/Quest-SPA',
//     muted: 'Website',
// },
// {
//     id:14,
//     img: '/img/suse-600x380.jpg',
//     title: 'Ingram Suse',
//     desc: 'Soluciones en trabajo digital.',
//     link: 'https://latam.ingrammicro.com/SUSE_SPA',
//     muted: 'Website',
// },
// {
//     id:13,
//     img: '/img/iecs-600x380.jpg',
//     title: 'Ingram ECS 2021',
//     desc: 'Sitio web de evento anual.',
//     link: 'https://latam.ingrammicro.com/EnglishCaribbeanSummit2021',
//     muted: 'Website',
// },
// {
//     id:12,
//     img: '/img/aruba-600x380.jpg',
//     title: 'Aruba ESP',
//     desc: 'Sitio web de plataforma de servicios.',
//     link: 'https://latam.ingrammicro.com/Aruba_ESP-SPA',
//     muted: 'Website',
// },
// {
//     id:11,
//     img: '/img/hpe-600x380.jpg',
//     title: 'Hewlett Packard Enterprise',
//     desc: 'Diversas soluciones en la nube de HP.',
//     link: 'https://latam.ingrammicro.com/HPE_Home',
//     muted: 'Website',
// },
// {
//     id:10,
//     img: '/img/axis-600x380.jpg',
//     title: 'Axis',
//     desc: 'Soluciones de videovigilancia.',
//     link: 'https://latam.ingrammicro.com/AxisCommunications_SPA',
//     muted: 'Website',
// },
// {
//     id:9,
//     img: '/img/zebra-600x380.jpg',
//     title: 'Zebra',
//     desc: 'Sitio web de Zebra Retail.',
//     link: 'https://latam.ingrammicro.com/ZebraRetail_SPA',
//     muted: 'Website',
// },
// {
//     id:8,
//     img: '/img/fermina-600x380.jpg',
//     title: 'Fermina',
//     desc: 'Sitio web de moda con carrito de compra.',
//     link: 'https://tiendafermina.com.ar',
//     muted: 'Wordpress',
// },
// {
//     id:7,
//     img: '/img/moreno-600x380.jpg',
//     title: 'Moreno Andrología',
//     desc: 'Sitio web personal de medicina.',
//     link: 'https://morenoandrologia.com.ar',
//     muted: 'Wordpress',
// },
// {
//     id:6,
//     img: '/img/ucl-600x380.jpg',
//     title: 'UCL Play',
//     desc: 'Magazine con streaming de video 24hs.',
//     link: 'https://www.ucltelevision.com/',
//     muted: 'Wordpress',
// },

// {
//     id:4,
//     img: '/img/dorian-600x380.jpg',
//     title: 'Dorian Body Care',
//     desc: 'Sitio institucional multi lenguaje.',
//     link: 'https://dorianbodycare.com',
//     muted: 'Wordpress + Drupal',
// },
// {
//     id:3,
//     img: '/img/alskar-600x380.jpg',
//     title: 'Älskar Digital Solutions',
//     desc: 'Sitio institucional de agencia digital.',
//     link: 'https://byalskar.com',
//     muted: 'Wordpress',
// },
// {
//     id:2,
//     img: '/img/limerick-600x380.jpg',
//     title: 'Colegio Limerick',
//     desc: 'Sitio institucional.',
//     link: 'limerick',
//     muted: 'HTML5',
// },
// {
//     id:1,
//     img: '/img/lincoln-600x380.jpg',
//     title: 'Lincoln Winds',
//     desc: 'Sitio institucional.',
//     link: 'https://lincolnwinds.com.ar',
//     muted: 'Wordpress',
// },
    ]
}
export default data_archive;